name: 'Terraform_oci_vcn'

on:
  push:
    branches: [ "git_actions" ]
    paths:
      - 'terraform-provider-oci/create-vcn/*tf'         
env:
  TF_VAR_tenancy_ocid: ${{ secrets.TENANCY_OCID }}  
  TF_VAR_user_ocid: ${{ secrets.USER_OCID }}
  TF_VAR_private_key: ${{ secrets.PRIVATE_KEY }}
  TF_VAR_ssh_public_key: ${{ secrets.SSH_PUBLIC_KEY }}
  TF_VAR_compartment_ocid: ${{ secrets.USER_OCID }}
  TF_VAR_fingerprint: ${{ secrets.FINGERPRINT }}
  STACK_DIR: ${{ vars.TF_STACK_DIR }}
  
#defaults:
 #run:
 
# permissions:
#  contents: read

jobs:
  terraform_setup:
    name: 'Terraform_setup'
    runs-on: ubuntu-latest
    environment: oci-labs
  # Use default shell and working directory regardless of the os of the GitHub Actions runner 
    defaults:
      run:
        shell: bash
        working-directory: ${{ env.STACK_DIR }}

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v3

    # Install the latest version of Terraform CLI and configure the Terraform CLI configuration file with a Terraform Cloud user API token
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.0.3
        terraform_wrapper: false
           # cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }} --> Terraform cloud
    
    # Create a cache for the terraform pluggin 
    - name: Config Terraform plugin cache
      run: |
        echo 'plugin_cache_dir="$HOME/.terraform.d/plugin-cache"' >~/.terraformrc
        mkdir --parents ~/.terraform.d/plugin-cache
    - name: Cache Terraform
      uses: actions/cache@v3
      with:
        path: |
          ~/.terraform.d/plugin-cache
        key: ${{ runner.os }}-terraform-${{ hashFiles('**/.terraform.lock.hcl') }}
        restore-keys: |
          ${{ runner.os }}-terraform-                
     
    # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
    - name: Terraform Init
      run: |
        echo ***** Terraform working directory is git.stack_dir: $GITHUB_WORKSPACE/${{ vars.TF_STACK_DIR }} ******
        pwd
        # cd $GITHUB_WORKSPACE/$STACK_DIR
        terraform init
        terraform -v 
  
    - name: Terraform format
      run: |
        echo  ***** Validate the Terraform configuration in $STACK_DIR  ******
        terraform validate
