name: 'Terraform_oci_vcn'

on:
  push:
    branches: [ "git_actions" ]
    paths:
      - './github/workflow/test_secret.yml'    

jobs:
  test_job:
    name: 'test secret job'
    runs-on: ubuntu-latest
    environment: test-labs
  # Use default shell and working directory regardless of the os of the GitHub Actions runner 
    defaults:
     run:
       shell: bash
    steps:   
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v3   
     # Show how to print unmasked GitHub secrets to the console
    - name: Step 1 - Echo out a GitHub Actions Secret to the logs
      run: |
        echo ${{ secrets.TEST_TOKEN }}
        echo "Trick to echo GitHub Actions Secret:  "   # ==> this will show ******
        echo ${{secrets.SECRET_TOKEN}} | sed 's/./& /g'  # ===> this will show the real content with space 'M Y P a s s w o r d'
