name: 'My_secret_test_Workflow'
on:
  push:
    branches: [ "git_actions" ]
    paths:
      - '.github/workflows/test_secret.yml'    

jobs:
  job_test_secrets:
 #   name: 'test secrets jobs'
    runs-on: ubuntu-latest
    environment: test-labs
  # Use default shell and working directory regardless of the os of the GitHub Actions runner 
    defaults:
     run:
       shell: bash
    steps:   
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v3   
     # Show how to print unmasked GitHub secrets to the console
    - name: Step 1 - Echo out a GitHub Actions Secret to the logs
      run: |
        echo ${{ secrets.TEST_SECRET }}
        # ==> this will show ******
        echo "Trick to echo GitHub Actions Secret:  "   
        # ===> this will show the real content with space 'M Y P a s s w o r d'
        echo ${{secrets.TEST_SECRET}} | sed 's/./& /g'  
 
#  job2:
#    runs-on: ubuntu-latest
#    environment: test-labs
#    steps:   
#    # Checkout the repository to the GitHub Actions runner
#    - name: Checkout
#      uses: actions/checkout@v3    
